spring.application.name=Mail-Sending

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shanukushwah845@gmail.com
spring.mail.password=calw omtz ycdy wreb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
